# Generated by Django 4.1.3 on 2022-12-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_style', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='html_code',
            field=models.CharField(blank=True, db_index=True, max_length=7, unique=True, verbose_name='HTML code'),
        ),
    ]
