# Generated by Django 4.1.3 on 2022-12-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_code', models.CharField(blank=True, db_index=True, max_length=7, unique=True, verbose_name='HTML code')),
                ('red', models.PositiveSmallIntegerField(default=0, verbose_name='red')),
                ('green', models.PositiveSmallIntegerField(default=0, verbose_name='green')),
                ('blue', models.PositiveSmallIntegerField(default=0, verbose_name='blue')),
                ('alpha', models.DecimalField(decimal_places=4, default=1, max_digits=5, verbose_name='alpha')),
                ('name', models.SlugField(blank=True, null=True, verbose_name='name')),
                ('used_for_tech_categories', models.BooleanField(default=False, verbose_name='used for technology categories')),
                ('used_for_logo_designs', models.BooleanField(default=True, verbose_name='used for logo designs')),
                ('used_for_ui_schemes', models.BooleanField(default=False, verbose_name='used for UI schemes')),
                ('used_as_main_system', models.BooleanField(default=False, verbose_name='Used as main system color')),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
                'ordering': ('html_code',),
            },
        ),
    ]
