# Generated by Django 4.1.3 on 2022-12-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ('base_cost', 'rarity', 'id'), 'verbose_name': 'technology', 'verbose_name_plural': 'technologies'},
        ),
    ]
