# Generated by Django 4.1.3 on 2022-12-05 14:48

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_style', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('color', models.ForeignKey(default='#cccccc', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tech_branches', to='config_style.color', to_field='html_code', verbose_name='color')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', tinymce.models.HTMLField(max_length=4000, verbose_name='description')),
                ('base_cost', models.PositiveSmallIntegerField(db_index=True, default=1000, verbose_name='base cost')),
                ('rarity', models.PositiveIntegerField(default=100, verbose_name='rarity')),
                ('starting', models.BooleanField(default=False, verbose_name='starting technology')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='technology.branch', verbose_name='branch')),
            ],
            options={
                'verbose_name': 'technology',
                'verbose_name_plural': 'technologies',
                'ordering': ('base_cost', 'rarity', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='technology.technology', verbose_name='depends on')),
                ('target_technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='technology.technology', verbose_name='target technology')),
            ],
            options={
                'verbose_name': 'dependency',
                'verbose_name_plural': 'dependencies',
                'ordering': ('target_technology', 'dependency'),
            },
        ),
        migrations.CreateModel(
            name='Catalyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=250, null=True, verbose_name='event')),
                ('rarity_base_modifier', models.IntegerField(default=0, verbose_name='rarity base modifier')),
                ('rarity_divisive_modifier', models.DecimalField(decimal_places=4, default=1, max_digits=5, verbose_name='rarity divisive modifier')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalysts', to='technology.technology', verbose_name='technology')),
            ],
            options={
                'verbose_name': 'catalyst',
                'verbose_name_plural': 'catalysts',
                'ordering': ('technology', 'id'),
            },
        ),
    ]
