# Generated by Django 4.1.3 on 2022-12-05 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='technology.branch', verbose_name='parent branch'),
        ),
        migrations.AddField(
            model_name='technology',
            name='level',
            field=models.SmallIntegerField(default=0, verbose_name='level'),
        ),
    ]
