# Generated by Django 4.1.3 on 2022-12-06 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0002_branch_parent_technology_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ('level', 'base_cost', 'rarity', 'id'), 'verbose_name': 'technology', 'verbose_name_plural': 'technologies'},
        ),
        migrations.AddField(
            model_name='catalyst',
            name='has_tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technology.technology', verbose_name='has technology'),
        ),
        migrations.AddField(
            model_name='catalyst',
            name='research_progress_fixed',
            field=models.IntegerField(default=0, verbose_name='fixed research progress'),
        ),
        migrations.AddField(
            model_name='catalyst',
            name='research_progress_partial',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='partial research progress'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='base_cost',
            field=models.PositiveIntegerField(db_index=True, default=1000, verbose_name='base cost'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], db_index=True, default=0, verbose_name='level'),
        ),
    ]
